##prueba: "@project.java.version@"

env: "DEV"
project: "@project.artifactId@"
api: "api-luciano"
logging:
  level:
    org.springframework: ERROR
    com.duoc: DEBUG
  pattern:
    console: "${api}${project};${env};%-5level;[%thread] - %logger{36}.%M - %msg%n"

spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(Host = localhost)(Port = 1521)))(CONNECT_DATA =(SERVICE_NAME = ORCLCDB.localdomain)(SERVER=dedicated)))
    username: luciano
    password: luciano
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.Oracle10gDialect
        proc:
          param_null_passing: true
    show-sql: true
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
